# Generated by Django 4.2.1 on 2024-01-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_title', models.CharField(max_length=255)),
                ('service_image', models.ImageField(upload_to='backend/services/images')),
                ('service_description', models.TextField()),
                ('support_image', models.ImageField(upload_to='backend/services/images/support_images')),
            ],
        ),
    ]
