# Generated by Django 4.2.1 on 2024-01-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='support_image2',
            field=models.ImageField(default='', upload_to='backend/services/images/support_images'),
        ),
    ]
