# Generated by Django 4.2.1 on 2024-01-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_service_support_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='additional_content_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='additional_content_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='additional_content_title_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='additional_content_title_2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
