# Generated by Django 4.2.1 on 2024-01-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_customeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='blog_id',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
