# Generated by Django 4.2.1 on 2024-02-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_customeuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='blog_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
