# Generated by Django 4.2.1 on 2023-12-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='reason_text',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
