# Generated by Django 4.2.1 on 2023-12-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_customeuser_reason_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='pin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='reason',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='reason_text',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
